import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Header, { HeaderProps } from "@/components/header";
import clsx from "clsx";
import React from "react";
import { defaultLocale } from "../i18n";
import { getDocumentBySlug } from "outstatic/server";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: {
    lang: string;
  }
}>) {
  const lang = params.lang ?? defaultLocale;
  const siteInfo = getDocumentBySlug('siteinfo', lang, ['title', 'description', 'coverImage']);
  const headerProps: HeaderProps = {
    logoUrl: siteInfo?.coverImage ?? '',
    siteTitle: siteInfo?.title ?? '',
    navLinks: [{ url: '/', label: 'Home' }, { url: '#', label: 'About' }, { url: '#', label: 'Services' }, { url: '#', label: 'Contact' }],
    lang: lang,
  }
  return (
    <html lang={lang}>
      <body
        className={clsx(`${geistSans.variable} ${geistMono.variable} antialiased`,
          "flex flex-col min-h-screen text-slate-900 dark:text-slate-400 bg-white dark:bg-slate-900"
        )}
      >
        <Header {...headerProps} lang={lang} />
        {children}
        <Footer {...headerProps} lang={lang} />
      </body>
    </html>
  );
}
